/**
 * @file StrategyEngine.hpp
 * @brief CRTP-based strategy engine framework.
 *
 * Implements the Curiously Recurring Template Pattern (CRTP) for
 * strategy dispatch, avoiding virtual function overhead on the hot path.
 *
 * Why CRTP over virtual functions:
 * - Eliminates vtable lookup (cache miss) on every signal
 * - Enables compiler inlining of strategy logic
 * - Zero-cost abstraction at runtime
 * - Compile-time polymorphism for strategy composition
 *
 * @author HFT NanoTick Team
 * @copyright MIT License
 */

#ifndef HFT_NANOTICK_STRATEGY_ENGINE_HPP
#define HFT_NANOTICK_STRATEGY_ENGINE_HPP

#include "../core/Types.hpp"
#include "../core/Timestamp.hpp"
#include "../orderbook/OrderBook.hpp"

#include <array>
#include <cstddef>
#include <cmath>
#include <utility>
#include <vector>

namespace hft {

//==============================================================================
// Strategy Order Request
//==============================================================================

/**
 * @brief Order request generated by strategy.
 *
 * Represents the strategy's intent to trade, which will be sent
 * to the order entry gateway for execution.
 */
struct alignas(CACHE_LINE_SIZE) OrderRequest {
    SymbolId  symbolId; ///< Target instrument
    Side      side; ///< Buy or Sell
    Price     price; ///< Limit price (0 for market)
    Quantity  quantity; ///< Order quantity
    OrderType orderType; ///< Order type
    Timestamp requestTime; ///< Strategy signal timestamp
    std::uint64_t strategyId; ///< Originating strategy ID

    OrderRequest() noexcept = default;

    OrderRequest(SymbolId sym, Side s, Price p, Quantity q,
                 OrderType type = OrderType::Limit) noexcept
        : symbolId(sym)
        , side(s)
        , price(p)
        , quantity(q)
        , orderType(type)
        , requestTime(nowNanos())
        , strategyId(0)
    {}
};

//==============================================================================
// Fixed-Capacity Order Batch
//==============================================================================

/**
 * @brief Small fixed-capacity container for strategy-generated orders.
 *
 * This is the hot-path strategy output type. It avoids heap allocation while
 * preserving the minimal vector-like API used by strategies and tests.
 */
template <std::size_t Capacity>
class OrderRequestBatch {
public:
    static_assert(Capacity > 0, "Capacity must be greater than zero");

    [[nodiscard]] constexpr std::size_t size() const noexcept { return m_size; }
    [[nodiscard]] constexpr bool empty() const noexcept { return m_size == 0; }
    [[nodiscard]] static constexpr std::size_t capacity() noexcept { return Capacity; }

    void clear() noexcept { m_size = 0; }

    [[nodiscard]] bool push_back(const OrderRequest& request) noexcept {
        if (m_size >= Capacity) [[unlikely]] {
            return false;
        }
        m_orders[m_size++] = request;
        return true;
    }

    template <typename... Args>
    [[nodiscard]] bool emplace_back(Args&&... args) noexcept {
        if (m_size >= Capacity) [[unlikely]] {
            return false;
        }
        m_orders[m_size++] = OrderRequest(std::forward<Args>(args)...);
        return true;
    }

    [[nodiscard]] OrderRequest& operator[](std::size_t index) noexcept {
        return m_orders[index];
    }

    [[nodiscard]] const OrderRequest& operator[](std::size_t index) const noexcept {
        return m_orders[index];
    }

    [[nodiscard]] OrderRequest* begin() noexcept { return m_orders.data(); }
    [[nodiscard]] OrderRequest* end() noexcept { return m_orders.data() + m_size; }
    [[nodiscard]] const OrderRequest* begin() const noexcept { return m_orders.data(); }
    [[nodiscard]] const OrderRequest* end() const noexcept { return m_orders.data() + m_size; }

private:
    std::array<OrderRequest, Capacity> m_orders{};
    std::size_t m_size{0};
};

//==============================================================================
// Strategy Signal
//==============================================================================

/**
 * @brief Trading signal from strategy analysis.
 */
enum class Signal : std::int8_t {
    None       = 0,
    BuySpot    = 1, ///< Buy spot instrument
    SellSpot   = -1, ///< Sell spot instrument
    BuyFuture  = 2, ///< Buy futures contract
    SellFuture = -2 ///< Sell futures contract
};

/**
 * @brief Strategy state machine states.
 */
enum class StrategyState : std::uint8_t {
    Idle       = 0, ///< Not trading
    Active     = 1, ///< Actively generating signals
    Paused     = 2, ///< Temporarily paused
    Stopped    = 3, ///< Stopped, no trading
    Error      = 4 ///< Error state
};

//==============================================================================
// Strategy Statistics
//==============================================================================

/**
 * @brief Runtime statistics for strategy monitoring.
 */
struct alignas(CACHE_LINE_SIZE) StrategyStats {
    std::atomic<std::uint64_t> ticksProcessed{0};
    std::atomic<std::uint64_t> signalsGenerated{0};
    std::atomic<std::uint64_t> ordersSubmitted{0};
    std::atomic<std::uint64_t> ordersFilled{0};
    std::atomic<std::uint64_t> ordersRejected{0};
    std::atomic<std::int64_t> realizedPnl{0}; ///< Fixed-point P&L
    std::atomic<std::int64_t> unrealizedPnl{0}; ///< Fixed-point P&L

    void reset() noexcept {
        ticksProcessed.store(0, std::memory_order_relaxed);
        signalsGenerated.store(0, std::memory_order_relaxed);
        ordersSubmitted.store(0, std::memory_order_relaxed);
        ordersFilled.store(0, std::memory_order_relaxed);
        ordersRejected.store(0, std::memory_order_relaxed);
        realizedPnl.store(0, std::memory_order_relaxed);
        unrealizedPnl.store(0, std::memory_order_relaxed);
    }
};

//==============================================================================
// CRTP Strategy Base Class
//==============================================================================

/**
 * @brief CRTP base class for trading strategies.
 *
 * Provides common infrastructure for all strategies with compile-time
 * dispatch via CRTP. Derived classes implement the actual trading logic
 * by overriding the CRTP hook methods.
 *
 * Key CRTP hooks:
 * - onTick(): Called on each market data update
 * - computeSignal(): Generate trading signal from market state
 * - onOrderFill(): Handle order fill notifications
 *
 * @tparam Derived The derived strategy class.
 */
template <typename Derived>
class StrategyBase {
public:
    static constexpr std::size_t MAX_ORDERS_PER_SIGNAL = 4;
    using OrderBatch = OrderRequestBatch<MAX_ORDERS_PER_SIGNAL>;

    /**
     * @brief Construct strategy base.
     * @param strategyId Unique strategy identifier.
     */
    explicit StrategyBase(std::uint64_t strategyId = 0) noexcept
        : m_strategyId(strategyId)
        , m_state(StrategyState::Idle)
    {}

    virtual ~StrategyBase() = default;

    // Non-copyable
    StrategyBase(const StrategyBase&) = delete;
    StrategyBase& operator=(const StrategyBase&) = delete;

    //==========================================================================
    // Strategy Lifecycle
    //==========================================================================

    /**
     * @brief Initialize the strategy.
     *
     * Called once before trading starts. Derived classes should
     * perform initialization here.
     *
     * @return true if initialization succeeded.
     */
    [[nodiscard]] bool initialize() noexcept {
        if (m_state != StrategyState::Idle && m_state != StrategyState::Stopped) {
            return false;
        }

        // CRTP: Call derived class initialization
        bool result = static_cast<Derived*>(this)->onInitialize();

        if (result) {
            m_state = StrategyState::Active;
            m_stats.reset();
        } else {
            m_state = StrategyState::Error;
        }

        return result;
    }

    /**
     * @brief Stop the strategy.
     */
    void stop() noexcept {
        m_state = StrategyState::Stopped;
        static_cast<Derived*>(this)->onStop();
    }

    /**
     * @brief Pause the strategy (stops signal generation).
     */
    void pause() noexcept {
        if (m_state == StrategyState::Active) {
            m_state = StrategyState::Paused;
        }
    }

    /**
     * @brief Resume a paused strategy.
     */
    void resume() noexcept {
        if (m_state == StrategyState::Paused) {
            m_state = StrategyState::Active;
        }
    }

    //==========================================================================
    // Market Data Processing
    //==========================================================================

    /**
     * @brief Process a market data tick.
     *
     * Main entry point for market data. Performs state checks and
     * dispatches to derived class via CRTP.
     *
     * @param update Order book update.
     * @return Generated order requests (may be empty).
     */
    template <std::size_t Capacity>
    std::size_t onMarketDataInto(const OrderBookUpdate& update,
                                 OrderRequestBatch<Capacity>& orders) noexcept {
        orders.clear();

        if (m_state != StrategyState::Active) [[unlikely]] {
            return 0;
        }

        m_stats.ticksProcessed.fetch_add(1, std::memory_order_relaxed);

        // CRTP: Call derived class tick handler
        static_cast<Derived*>(this)->onTick(update);

        // CRTP: Compute trading signal
        Signal signal = static_cast<Derived*>(this)->computeSignal();

        if (signal != Signal::None) {
            m_stats.signalsGenerated.fetch_add(1, std::memory_order_relaxed);

            // CRTP: Generate order(s) from signal into caller-provided storage
            static_cast<Derived*>(this)->generateOrdersInto(signal, orders);

            for (auto& order : orders) {
                order.strategyId = m_strategyId;
                order.requestTime = nowNanos();
            }
        }

        return orders.size();
    }

    /**
     * @brief Compatibility wrapper that returns std::vector for existing callers.
     *
     * Production hot paths should call onMarketDataInto() with caller-owned
     * storage to avoid heap allocation.
     */
    std::vector<OrderRequest> onMarketData(const OrderBookUpdate& update) noexcept {
        OrderBatch batch;
        (void)onMarketDataInto(update, batch);

        std::vector<OrderRequest> orders;
        orders.reserve(batch.size());
        for (const auto& order : batch) {
            orders.push_back(order);
        }
        return orders;
    }

    //==========================================================================
    // Order Management Callbacks
    //==========================================================================

    /**
     * @brief Handle order fill notification.
     * @param orderId Filled order ID.
     * @param fillPrice Execution price.
     * @param fillQty Filled quantity.
     */
    void handleOrderFill(OrderId orderId, Price fillPrice, Quantity fillQty) noexcept {
        m_stats.ordersFilled.fetch_add(1, std::memory_order_relaxed);
        static_cast<Derived*>(this)->onOrderFill(orderId, fillPrice, fillQty);
    }

    /**
     * @brief Handle order rejection.
     * @param orderId Rejected order ID.
     * @param reason Rejection reason code.
     */
    void handleOrderReject(OrderId orderId, int reason) noexcept {
        m_stats.ordersRejected.fetch_add(1, std::memory_order_relaxed);
        static_cast<Derived*>(this)->onOrderReject(orderId, reason);
    }

    //==========================================================================
    // Accessors
    //==========================================================================

    [[nodiscard]] std::uint64_t strategyId() const noexcept { return m_strategyId; }
    [[nodiscard]] StrategyState state() const noexcept { return m_state; }
    [[nodiscard]] const StrategyStats& stats() const noexcept { return m_stats; }
    [[nodiscard]] bool isActive() const noexcept { return m_state == StrategyState::Active; }

protected:
    // Default CRTP implementations (can be overridden)
    bool onInitialize() noexcept { return true; }
    void onStop() noexcept {}
    void onTick([[maybe_unused]] const OrderBookUpdate& update) noexcept {}
    Signal computeSignal() noexcept { return Signal::None; }
    std::vector<OrderRequest> generateOrders([[maybe_unused]] Signal signal) noexcept { return {}; }
    template <std::size_t Capacity>
    void generateOrdersInto([[maybe_unused]] Signal signal,
                            [[maybe_unused]] OrderRequestBatch<Capacity>& orders) noexcept {}
    void onOrderFill([[maybe_unused]] OrderId orderId,
                     [[maybe_unused]] Price fillPrice,
                     [[maybe_unused]] Quantity fillQty) noexcept {}
    void onOrderReject([[maybe_unused]] OrderId orderId,
                       [[maybe_unused]] int reason) noexcept {}

    std::uint64_t m_strategyId;
    StrategyState m_state;
    StrategyStats m_stats;
};

//==============================================================================
// Cash and Carry Arbitrage Strategy
//==============================================================================

/**
 * @brief Configuration for Cash and Carry arbitrage.
 */
struct CashCarryConfig {
    Price entryThreshold{priceFromDouble(0.001)}; ///< Min spread for entry (0.1%)
    Price exitThreshold{priceFromDouble(0.0002)}; ///< Exit when spread < this
    Quantity defaultQty{100}; ///< Default order size
    Quantity maxPosition{1000}; ///< Max position per leg
    Timestamp maxHoldingPeriodNanos{300'000'000'000}; ///< 5 minutes
};

/**
 * @brief Spot-Futures Cash and Carry Arbitrage Strategy.
 *
 * Implements the classic cash-and-carry arbitrage:
 * - Buy spot / Sell future when futures premium exceeds threshold
 * - Sell spot / Buy future when spot premium exceeds threshold
 *
 * This strategy exploits the basis (price difference) between spot
 * and futures markets, which should converge at expiration.
 *
 * Signal Logic:
 * - If (Futures_Bid - Spot_Ask) > Threshold: Buy Spot, Sell Future
 * - If (Spot_Bid - Futures_Ask) > Threshold: Sell Spot, Buy Future
 */
class CashCarryArbitrage : public StrategyBase<CashCarryArbitrage> {
public:
    using Base = StrategyBase<CashCarryArbitrage>;

    /**
     * @brief Construct Cash and Carry arbitrage strategy.
     *
     * @param spotBook Pointer to spot order book.
     * @param futuresBook Pointer to futures order book.
     * @param config Strategy configuration.
     * @param strategyId Unique strategy ID.
     */
    CashCarryArbitrage(DefaultOrderBook* spotBook,
                       DefaultOrderBook* futuresBook,
                       const CashCarryConfig& config = {},
                       std::uint64_t strategyId = 1) noexcept
        : Base(strategyId)
        , m_spotBook(spotBook)
        , m_futuresBook(futuresBook)
        , m_config(config)
    {}

    //==========================================================================
    // CRTP Hook Implementations
    //==========================================================================

    bool onInitialize() noexcept {
        if (!m_spotBook || !m_futuresBook) {
            return false;
        }

        m_spotPosition = 0;
        m_futuresPosition = 0;
        m_entryTime = 0;
        m_lastSignal = Signal::None;

        return true;
    }

    void onTick(const OrderBookUpdate& update) noexcept {
        // Update internal state tracking
        (void)update;

        // Cache current BBO for signal computation
        m_spotBid = m_spotBook->bestBid();
        m_spotAsk = m_spotBook->bestAsk();
        m_futuresBid = m_futuresBook->bestBid();
        m_futuresAsk = m_futuresBook->bestAsk();
    }

    /**
     * @brief Compute arbitrage signal from current market state.
     *
     * Core strategy logic implementing Cash and Carry arbitrage.
     *
     * @return Trading signal or Signal::None.
     */
    Signal computeSignal() noexcept {
        // Ensure we have valid prices on both sides
        if (m_spotBid == INVALID_PRICE || m_spotAsk == INVALID_PRICE ||
            m_futuresBid == INVALID_PRICE || m_futuresAsk == INVALID_PRICE) {
            return Signal::None;
        }

        // Check position limits
        if (std::abs(m_spotPosition) >= m_config.maxPosition ||
            std::abs(m_futuresPosition) >= m_config.maxPosition) {
            return Signal::None;
        }

        //======================================================================
        // Cash and Carry: Buy Spot / Sell Futures
        //======================================================================
        // When futures trade at a premium to spot, we can lock in the basis
        // by buying spot (cheaper) and selling futures (more expensive)

        Price futuresSpotSpread = m_futuresBid - m_spotAsk;

        if (futuresSpotSpread > m_config.entryThreshold) {
            // Profitable to: Buy Spot at Ask, Sell Futures at Bid
            m_lastSignal = Signal::BuySpot; // Will pair with SellFuture
            return Signal::BuySpot;
        }

        //======================================================================
        // Reverse Cash and Carry: Sell Spot / Buy Futures
        //======================================================================
        // When spot trades at a premium to futures (backwardation),
        // we can profit by selling spot and buying futures

        Price spotFuturesSpread = m_spotBid - m_futuresAsk;

        if (spotFuturesSpread > m_config.entryThreshold) {
            // Profitable to: Sell Spot at Bid, Buy Futures at Ask
            m_lastSignal = Signal::SellSpot; // Will pair with BuyFuture
            return Signal::SellSpot;
        }

        //======================================================================
        // Exit Check: Close position when basis collapses
        //======================================================================
        if (m_spotPosition != 0) {
            Price currentBasis = (m_spotPosition > 0)
                ? (m_futuresBid - m_spotAsk) // Long spot, need to sell
                : (m_spotBid - m_futuresAsk); // Short spot, need to buy

            if (currentBasis < m_config.exitThreshold) {
                // Basis has collapsed, close position
                m_lastSignal = (m_spotPosition > 0) ? Signal::SellSpot : Signal::BuySpot;
                return m_lastSignal;
            }

            // Check holding period timeout
            if (m_entryTime > 0) {
                Timestamp elapsed = nowNanos() - m_entryTime;
                if (elapsed > m_config.maxHoldingPeriodNanos) {
                    m_lastSignal = (m_spotPosition > 0) ? Signal::SellSpot : Signal::BuySpot;
                    return m_lastSignal;
                }
            }
        }

        return Signal::None;
    }

    /**
     * @brief Generate paired orders for arbitrage.
     *
     * Arbitrage requires simultaneous orders in both markets.
     *
     * @param signal Trading signal.
     * @return Vector of order requests (typically 2 for arb).
     */
    template <std::size_t Capacity>
    void generateOrdersInto(Signal signal, OrderRequestBatch<Capacity>& orders) noexcept {
        Quantity qty = m_config.defaultQty;

        switch (signal) {
            case Signal::BuySpot:
                // Buy Spot at Ask
                (void)orders.emplace_back(m_spotBook->symbolId(), Side::Buy, m_spotAsk, qty, OrderType::Limit);
                // Sell Futures at Bid
                (void)orders.emplace_back(m_futuresBook->symbolId(), Side::Sell, m_futuresBid, qty, OrderType::Limit);
                break;

            case Signal::SellSpot:
                // Sell Spot at Bid
                (void)orders.emplace_back(m_spotBook->symbolId(), Side::Sell, m_spotBid, qty, OrderType::Limit);
                // Buy Futures at Ask
                (void)orders.emplace_back(m_futuresBook->symbolId(), Side::Buy, m_futuresAsk, qty, OrderType::Limit);
                break;

            default:
                break;
        }
    }

    std::vector<OrderRequest> generateOrders(Signal signal) noexcept {
        OrderBatch batch;
        generateOrdersInto(signal, batch);

        std::vector<OrderRequest> orders;
        orders.reserve(batch.size());
        for (const auto& order : batch) {
            orders.push_back(order);
        }
        return orders;
    }

    void onOrderFill(OrderId orderId, Price fillPrice, Quantity fillQty) noexcept {
        // Update position tracking
        // In production, we'd need to track which order belongs to which leg
        (void)orderId;
        (void)fillPrice;

        if (m_lastSignal == Signal::BuySpot) {
            m_spotPosition += fillQty;
            m_futuresPosition -= fillQty;
            if (m_entryTime == 0) m_entryTime = nowNanos();
        } else if (m_lastSignal == Signal::SellSpot) {
            m_spotPosition -= fillQty;
            m_futuresPosition += fillQty;
            if (m_entryTime == 0) m_entryTime = nowNanos();
        }

        // Check if position is flat
        if (m_spotPosition == 0 && m_futuresPosition == 0) {
            m_entryTime = 0;
        }
    }

    //==========================================================================
    // Strategy-Specific Accessors
    //==========================================================================

    [[nodiscard]] Quantity spotPosition() const noexcept { return m_spotPosition; }
    [[nodiscard]] Quantity futuresPosition() const noexcept { return m_futuresPosition; }

    [[nodiscard]] Price currentBasis() const noexcept {
        if (m_spotAsk == INVALID_PRICE || m_futuresBid == INVALID_PRICE) {
            return INVALID_PRICE;
        }
        return m_futuresBid - m_spotAsk;
    }

    void setConfig(const CashCarryConfig& config) noexcept {
        m_config = config;
    }

    [[nodiscard]] const CashCarryConfig& config() const noexcept {
        return m_config;
    }

private:
    DefaultOrderBook* m_spotBook;
    DefaultOrderBook* m_futuresBook;
    CashCarryConfig m_config;

    // Cached BBO prices
    Price m_spotBid{INVALID_PRICE};
    Price m_spotAsk{INVALID_PRICE};
    Price m_futuresBid{INVALID_PRICE};
    Price m_futuresAsk{INVALID_PRICE};

    // Position tracking
    Quantity m_spotPosition{0};
    Quantity m_futuresPosition{0};
    Timestamp m_entryTime{0};
    Signal m_lastSignal{Signal::None};
};

} // namespace hft

#endif // HFT_NANOTICK_STRATEGY_ENGINE_HPP
